/**
 * Sacred Path design system — lifted verbatim from the inline `tailwind.config`
 * that Google Stitch emitted in every `player/baseline/**\/code.html`, so the
 * utility classes copied out of those files (`px-container-margin`,
 * `text-headline-xl`, `font-body-md`, `bg-surface-container-lowest`, …) resolve
 * unchanged. See player/baseline/stitch_quest_expedition_ui/sacred_path_design_system/DESIGN.md.
 *
 * Only deviation: darkMode is "media" (Stitch emitted "class") so the app
 * follows the phone's system theme automatically — there is no toggle in any
 * of the provided designs.
 */
export default {
  darkMode: 'media',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        tertiary: '#22221e',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#1a1c1c',
        'on-error-container': '#93000a',
        'outline-variant': '#c2c8c2',
        'secondary-fixed-dim': '#ffb68c',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#f0f1f1',
        'surface-container-low': '#f3f3f4',
        'surface-container': '#eeeeee',
        'tertiary-fixed-dim': '#c9c6c0',
        'on-primary-container': '#90a598',
        'surface-tint': '#4f6358',
        'on-secondary-fixed': '#321200',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#0c1f16',
        'surface-container-high': '#e8e8e8',
        surface: '#f9f9f9',
        'on-background': '#1a1c1c',
        'inverse-primary': '#b6ccbe',
        'primary-container': '#283b31',
        'inverse-surface': '#2f3131',
        'on-tertiary-fixed-variant': '#484743',
        'on-tertiary-fixed': '#1c1c18',
        'surface-bright': '#f9f9f9',
        'on-primary-fixed-variant': '#384b40',
        'on-secondary-container': '#6d3000',
        'secondary-container': '#fc934f',
        secondary: '#994703',
        'surface-dim': '#dadada',
        'surface-variant': '#e2e2e2',
        'surface-container-highest': '#e2e2e2',
        'primary-fixed-dim': '#b6ccbe',
        'on-secondary-fixed-variant': '#753400',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#a2a09b',
        error: '#ba1a1a',
        'tertiary-container': '#383733',
        'primary-fixed': '#d2e8d9',
        'tertiary-fixed': '#e6e2dc',
        background: '#f9f9f9',
        outline: '#737874',
        'on-surface-variant': '#424844',
        primary: '#13251c',
        'on-error': '#ffffff',
        'secondary-fixed': '#ffdbc9',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'stack-md': '16px',
        unit: '8px',
        'container-margin': '24px',
        'stack-sm': '8px',
        gutter: '16px',
        'section-padding': '48px',
        'stack-lg': '32px',
      },
      fontFamily: {
        'body-lg': ['Inter'],
        'label-md': ['Inter'],
        'headline-lg': ['Playfair Display'],
        'body-md': ['Inter'],
        'headline-md': ['Playfair Display'],
        'headline-xl': ['Playfair Display'],
        'label-sm': ['Inter'],
        'headline-lg-mobile': ['Playfair Display'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
